// <auto-generated />
using System;
using Kwotty.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kwotty.Data.Migrations
{
    [DbContext(typeof(KwottyDbContext))]
    [Migration("20250414202352_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kwotty")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kwotty.Data.Entities.AccessToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiresOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AccessTokens", "kwotty");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MediumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MediumId");

                    b.ToTable("Authors", "kwotty");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NameSlug")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Categories", "kwotty");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.Medium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("CompleteUrl")
                        .HasMaxLength(1152)
                        .HasColumnType("nvarchar(1152)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FileName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Media", "kwotty");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Quotes", "kwotty");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.QuoteCategory", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuoteId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("QuotesCategories", "kwotty");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.QuoteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MediumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortNumber")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("TextSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("MediumId");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteItems", "kwotty");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.Rating", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("Value")
                        .HasColumnType("tinyint");

                    b.HasKey("QuoteId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings", "kwotty");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Firstname")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users", "kwotty");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.UserCategory", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("UsersCategories", "kwotty");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPauzed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastPausedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastResumedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings", "kwotty");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.Author", b =>
                {
                    b.HasOne("Kwotty.Data.Entities.Medium", "Medium")
                        .WithMany("Authors")
                        .HasForeignKey("MediumId");

                    b.Navigation("Medium");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.Quote", b =>
                {
                    b.HasOne("Kwotty.Data.Entities.Author", "Author")
                        .WithMany("Quotes")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.QuoteCategory", b =>
                {
                    b.HasOne("Kwotty.Data.Entities.Category", "Category")
                        .WithMany("QuoteCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kwotty.Data.Entities.Quote", "Quote")
                        .WithMany("QuoteCategories")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.QuoteItem", b =>
                {
                    b.HasOne("Kwotty.Data.Entities.Medium", "Medium")
                        .WithMany("QuoteItems")
                        .HasForeignKey("MediumId");

                    b.HasOne("Kwotty.Data.Entities.Quote", "Quote")
                        .WithMany("QuoteItems")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medium");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.Rating", b =>
                {
                    b.HasOne("Kwotty.Data.Entities.Quote", "Quote")
                        .WithMany("QuoteRatings")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kwotty.Data.Entities.User", "User")
                        .WithMany("QuoteRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.UserCategory", b =>
                {
                    b.HasOne("Kwotty.Data.Entities.Category", "Category")
                        .WithMany("UserCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kwotty.Data.Entities.UserSettings", "UserSettings")
                        .WithMany("UserCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.UserSettings", b =>
                {
                    b.HasOne("Kwotty.Data.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("Kwotty.Data.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.Author", b =>
                {
                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.Category", b =>
                {
                    b.Navigation("QuoteCategories");

                    b.Navigation("UserCategories");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.Medium", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("QuoteItems");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.Quote", b =>
                {
                    b.Navigation("QuoteCategories");

                    b.Navigation("QuoteItems");

                    b.Navigation("QuoteRatings");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.User", b =>
                {
                    b.Navigation("QuoteRatings");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Kwotty.Data.Entities.UserSettings", b =>
                {
                    b.Navigation("UserCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
